baseURL = 'https://yuandata.github.io/'
languageCode = 'en-us'
title = ''
theme = 'LoveIt'

[author]
name = "Alan"
[params]
defaultTheme = "light"

[params.header.title]
name = "Web Symphony"

[params.page.share]
enable = false

[params.footer]
enable = true
author = true
hugo = false
since = 2023

[params.home.profile]
title = "Web Symphony"
subtitle = "採用前後端分離架構，前端透過Hugo框架管理網站內容，後端使用Gin框架處理CRUD資料API。分離的架構使前端呈現更為流暢，後端數據處理更可靠高效。整體提升網站效能、可維護性，並便於擴展與迭代。"
typeit = false
