baseURL = 'https://yuandata.github.io/'
languageCode = 'en-us'
title = 'Shared Site'
theme = 'LoveIt'

[author]
  name = "Alan"
[params]
  [params.header]
    [params.header.title]
    typeit = false
  [params.page.share]
  enable = false
[params.footer]
    enable = true
    author = true
    hugo = false
    since = 2023
[params.home.profile]
    title = "My site"
    subtitle = "This is my site"
    typeit = false
